# Generated by Django 2.2.4 on 2019-10-09 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='A-01 ~ Z-999', max_length=16)),
                ('grand_total', models.IntegerField(help_text='총 합계(결제 금액)')),
                ('name', models.CharField(help_text='커피 외 n건', max_length=31)),
                ('orderer_request', models.CharField(help_text='고객님 요청사항', max_length=500)),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='가게 이름', max_length=64)),
                ('street_address', models.CharField(help_text='도로명 주소(신 주소)', max_length=128)),
                ('place', models.CharField(help_text='숭실대학교 학생회관 4층', max_length=64)),
                ('owner_phone', models.CharField(help_text='점주 전화번호', max_length=20)),
                ('note', models.TextField(blank=True, help_text='비고 등 기타 메모')),
                ('is_opened', models.BooleanField(default=False)),
                ('using_point_system', models.BooleanField(default=True)),
                ('store_detail', models.TextField(blank=True, default=list, help_text="가게 영업 시간, 휴무 등의 상세정보, [{'key': 'value'}] 형태")),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('priority', models.PositiveIntegerField(default=0, help_text='앱에 표시될 때의 우선순위')),
                ('description', models.CharField(blank=True, max_length=128)),
                ('default_price', models.IntegerField(default=3000)),
                ('category', models.CharField(max_length=16)),
                ('options', models.TextField(blank=True, default=list, help_text='이용 가능한 옵션')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='takeit_web.Store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.TextField(help_text='이용 가능한 옵션')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='takeit_web.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeit_web.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='takeit_web.Store'),
        ),
    ]
