# Generated by Django 2.2.4 on 2019-10-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeit_web', '0002_auto_20191009_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FAILURE_PAYMENT', '결제 실패'), ('WAITING_PAYMENT', '결제 대기중'), ('NEW', '새 주문'), ('REJECTED', '주문 거절'), ('IN_PROGRESS', '제조 중'), ('MANUFACTURED', '제조 완료'), ('DELIVERED', '전달 완료')], default='WAITING_PAYMENT', help_text='진행 상황', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='takeit_web.Order'),
        ),
    ]
