# Generated by Django 2.2.4 on 2019-10-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takeit_web', '0005_auto_20191011_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
